// This file is auto-generated by scripts/upload-overlays.ts
// DO NOT EDIT MANUALLY

/**
 * Cloudinary public IDs for overlay images
 * These are used to generate optimized URLs via getCldImageUrl
 */
export const OVERLAY_PUBLIC_IDS = [
  "/overlays/anime.webp",
  "/overlays/animeboy.png",
  "/overlays/animechar.png",
  "/overlays/animegirl.png",
  "/overlays/animegirl2.png",
  "/overlays/animegirl3.png",
  "/overlays/animegirl4.png",
  "/overlays/ash.webp",
  "/overlays/character.webp",
  "/overlays/chika.png",
  "/overlays/cute.png",
  "/overlays/dragonballz.png",
  "/overlays/girlpink.png",
  "/overlays/goku1.webp",
  "/overlays/goku2.webp",
  "/overlays/goku3.webp",
  "/overlays/luffy.webp",
  "/overlays/naruto.png",
  "/overlays/naruto1.webp",
  "/overlays/naruto2.webp",
  "/overlays/naruto3.webp",
  "/overlays/naruto4.png",
  "/overlays/naruto5.png",
  "/overlays/onepiece.png",
  "/overlays/onepiece.webp",
  "/overlays/onepiece2.png",
  "/overlays/onepunchman2.webp",
  "/overlays/onepunchman3.webp",
  "/overlays/overlay1.png",
  "/overlays/overlay2.png",
  "/overlays/overlay3.png",
  "/overlays/tanjiro.webp"
] as const;

/**
 * Mapping from original filename to Cloudinary public ID
 */
export const OVERLAY_MAPPING: Record<string, string> = {
  "anime.webp": "/overlays/anime.webp",
  "animeboy.png": "/overlays/animeboy.png",
  "animechar.png": "/overlays/animechar.png",
  "animegirl.png": "/overlays/animegirl.png",
  "animegirl2.png": "/overlays/animegirl2.png",
  "animegirl3.png": "/overlays/animegirl3.png",
  "animegirl4.png": "/overlays/animegirl4.png",
  "ash.webp": "/overlays/ash.webp",
  "character.webp": "/overlays/character.webp",
  "chika.png": "/overlays/chika.png",
  "cute.png": "/overlays/cute.png",
  "dragonballz.png": "/overlays/dragonballz.png",
  "girlpink.png": "/overlays/girlpink.png",
  "goku1.webp": "/overlays/goku1.webp",
  "goku2.webp": "/overlays/goku2.webp",
  "goku3.webp": "/overlays/goku3.webp",
  "luffy.webp": "/overlays/luffy.webp",
  "naruto.png": "/overlays/naruto.png",
  "naruto1.webp": "/overlays/naruto1.webp",
  "naruto2.webp": "/overlays/naruto2.webp",
  "naruto3.webp": "/overlays/naruto3.webp",
  "naruto4.png": "/overlays/naruto4.png",
  "naruto5.png": "/overlays/naruto5.png",
  "onepiece.png": "/overlays/onepiece.png",
  "onepiece.webp": "/overlays/onepiece.webp",
  "onepiece2.png": "/overlays/onepiece2.png",
  "onepunchman2.webp": "/overlays/onepunchman2.webp",
  "onepunchman3.webp": "/overlays/onepunchman3.webp",
  "overlay1.png": "/overlays/overlay1.png",
  "overlay2.png": "/overlays/overlay2.png",
  "overlay3.png": "/overlays/overlay3.png",
  "tanjiro.webp": "/overlays/tanjiro.webp"
};

/**
 * Get Cloudinary public ID for an overlay by filename
 */
export function getOverlayPublicId(filename: string): string | undefined {
  return OVERLAY_MAPPING[filename];
}

/**
 * Get all available overlay public IDs
 */
export function getAllOverlayPublicIds(): readonly string[] {
  return OVERLAY_PUBLIC_IDS;
}
