// This file is auto-generated by scripts/upload-backgrounds.ts
// DO NOT EDIT MANUALLY

export interface BackgroundCategory {
  [category: string]: string[];
}

export const backgroundCategories: BackgroundCategory = {
  "mac": [
    "/mac/mac-asset-1.jpeg",
    "/mac/mac-asset-10.jpg",
    "/mac/mac-asset-2.jpg",
    "/mac/mac-asset-3.jpg",
    "/mac/mac-asset-4.jpg",
    "/mac/mac-asset-5.jpg",
    "/mac/mac-asset-6.jpeg",
    "/mac/mac-asset-7.png",
    "/mac/mac-asset-8.jpg",
    "/mac/mac-asset-9.jpg"
  ],
  "nature": [
    "/nature/nature1.avif",
    "/nature/nature2.avif",
    "/nature/nature3.avif",
    "/nature/nature4.avif",
    "/nature/nature5.avif"
  ],
  "radiant": [
    "/radiant/radiant1.jpg",
    "/radiant/radiant10.jpg",
    "/radiant/radiant2.jpg",
    "/radiant/radiant3.jpg",
    "/radiant/radiant4.jpg",
    "/radiant/radiant5.jpg",
    "/radiant/radiant6.jpg",
    "/radiant/radiant7.avif",
    "/radiant/radiant8.jpg",
    "/radiant/radiant9.jpg"
  ],
  "mesh": [
    "/mesh/mesh1.webp",
    "/mesh/mesh2.webp",
    "/mesh/mesh3.webp",
    "/mesh/mesh4.webp",
    "/mesh/mesh5.webp",
    "/mesh/mesh6.webp",
    "/mesh/mesh7.webp",
    "/mesh/mesh8.webp"
  ],
  "demo": [
    "/demo/demo-1.png",
    "/demo/demo-10.png",
    "/demo/demo-11.png",
    "/demo/demo-12.png",
    "/demo/demo-13.png",
    "/demo/demo-14.png",
    "/demo/demo-15.png",
    "/demo/demo-2.png",
    "/demo/demo-3.png",
    "/demo/demo-4.png",
    "/demo/demo-5.png",
    "/demo/demo-6.png",
    "/demo/demo-7.png",
    "/demo/demo-8.png",
    "/demo/demo-9.png"
  ],
  "assets": [
    "/assets/asset-11.jpg",
    "/assets/asset-12.jpg",
    "/assets/asset-13.jpg",
    "/assets/asset-14.jpg",
    "/assets/asset-15.jpg",
    "/assets/asset-16.jpg",
    "/assets/asset-17.jpg",
    "/assets/asset-18.jpg",
    "/assets/asset-19.jpg",
    "/assets/asset-2.jpg",
    "/assets/asset-20.jpg",
    "/assets/asset-21.jpg",
    "/assets/asset-22.jpg",
    "/assets/asset-23.jpg",
    "/assets/asset-24.avif",
    "/assets/asset-25.jpg",
  ],
  "silk": [
    "/silk/amber.png",
    "/silk/dark.png",
    "/silk/monochrome.png",
    "/silk/silver.png",
    "/silk/sky.png"
  ]
};

export const cloudinaryPublicIds: string[] = [
  "backgrounds/backgrounds/mac/mac-asset-1",
  "backgrounds/backgrounds/mac/mac-asset-10",
  "backgrounds/backgrounds/mac/mac-asset-2",
  "backgrounds/backgrounds/mac/mac-asset-3",
  "backgrounds/backgrounds/mac/mac-asset-4",
  "backgrounds/backgrounds/mac/mac-asset-5",
  "backgrounds/backgrounds/mac/mac-asset-6",
  "backgrounds/backgrounds/mac/mac-asset-7",
  "backgrounds/backgrounds/mac/mac-asset-8",
  "backgrounds/backgrounds/mac/mac-asset-9",
  "backgrounds/backgrounds/nature/nature1",
  "backgrounds/backgrounds/nature/nature2",
  "backgrounds/backgrounds/nature/nature3",
  "backgrounds/backgrounds/nature/nature4",
  "backgrounds/backgrounds/nature/nature5",
  "backgrounds/backgrounds/radiant/radiant1",
  "backgrounds/backgrounds/radiant/radiant10",
  "backgrounds/backgrounds/radiant/radiant2",
  "backgrounds/backgrounds/radiant/radiant3",
  "backgrounds/backgrounds/radiant/radiant4",
  "backgrounds/backgrounds/radiant/radiant5",
  "backgrounds/backgrounds/radiant/radiant6",
  "backgrounds/backgrounds/radiant/radiant7",
  "backgrounds/backgrounds/radiant/radiant8",
  "backgrounds/backgrounds/radiant/radiant9",
  "backgrounds/backgrounds/mesh/mesh1",
  "backgrounds/backgrounds/mesh/mesh2",
  "backgrounds/backgrounds/mesh/mesh3",
  "backgrounds/backgrounds/mesh/mesh4",
  "backgrounds/backgrounds/mesh/mesh5",
  "backgrounds/backgrounds/mesh/mesh6",
  "backgrounds/backgrounds/mesh/mesh7",
  "backgrounds/backgrounds/mesh/mesh8",
  "backgrounds/backgrounds/demo/demo-1",
  "backgrounds/backgrounds/demo/demo-10",
  "backgrounds/backgrounds/demo/demo-11",
  "backgrounds/backgrounds/demo/demo-12",
  "backgrounds/backgrounds/demo/demo-13",
  "backgrounds/backgrounds/demo/demo-14",
  "backgrounds/backgrounds/demo/demo-15",
  "backgrounds/backgrounds/demo/demo-2",
  "backgrounds/backgrounds/demo/demo-3",
  "backgrounds/backgrounds/demo/demo-4",
  "backgrounds/backgrounds/demo/demo-5",
  "backgrounds/backgrounds/demo/demo-6",
  "backgrounds/backgrounds/demo/demo-7",
  "backgrounds/backgrounds/demo/demo-8",
  "backgrounds/backgrounds/demo/demo-9",
  "backgrounds/backgrounds/assets/asset-1",
  "backgrounds/backgrounds/assets/asset-10",
  "backgrounds/backgrounds/assets/asset-11",
  "backgrounds/backgrounds/assets/asset-12",
  "backgrounds/backgrounds/assets/asset-13",
  "backgrounds/backgrounds/assets/asset-14",
  "backgrounds/backgrounds/assets/asset-15",
  "backgrounds/backgrounds/assets/asset-16",
  "backgrounds/backgrounds/assets/asset-17",
  "backgrounds/backgrounds/assets/asset-18",
  "backgrounds/backgrounds/assets/asset-19",
  "backgrounds/backgrounds/assets/asset-2",
  "backgrounds/backgrounds/assets/asset-20",
  "backgrounds/backgrounds/assets/asset-21",
  "backgrounds/backgrounds/assets/asset-22",
  "backgrounds/backgrounds/assets/asset-23",
  "backgrounds/backgrounds/assets/asset-24",
  "backgrounds/backgrounds/assets/asset-25",
  "backgrounds/backgrounds/assets/asset-3",
  "backgrounds/backgrounds/assets/asset-4",
  "backgrounds/backgrounds/assets/asset-5",
  "backgrounds/backgrounds/assets/asset-6",
  "backgrounds/backgrounds/assets/asset-7",
  "backgrounds/backgrounds/assets/asset-8",
  "backgrounds/backgrounds/assets/asset-9",
  "backgrounds/backgrounds/silk/amber",
  "backgrounds/backgrounds/silk/dark",
  "backgrounds/backgrounds/silk/monochrome",
  "backgrounds/backgrounds/silk/silver",
  "backgrounds/backgrounds/silk/sky"
];

// Public ID for sign-in page background
export const SIGN_IN_BACKGROUND_PUBLIC_ID = 'backgrounds/backgrounds/mac/mac-asset-7';

// Public ID for sign-up page background
export const SIGN_UP_BACKGROUND_PUBLIC_ID = 'backgrounds/backgrounds/mac/mac-asset-2';

// Helper function to get all public IDs for a category
export function getBackgroundsByCategory(category: string): string[] {
  return backgroundCategories[category] || [];
}

// Helper function to get all available categories
export function getAvailableCategories(): string[] {
  return Object.keys(backgroundCategories);
}
